<?php
/**
 * Surya Vistaara Pvt. Ltd. (SVPL)
 * Database Management Controller — Backup, Restore, Data Purge & Demo Data Seeding
 */

namespace App\Controllers;

use App\Helpers\Response;
use App\Helpers\Database;
use App\Services\AuthService;
use App\Models\AuditLog;
use PDO;

class DatabaseController
{
    private function checkAccess(): array
    {
        $user = AuthService::user();
        if (!$user || !in_array($user['role'], ['SUPER_ADMIN', 'ADMIN', 'MANAGER'])) {
            Response::forbidden("Access Denied: Database management tools are restricted to Admin & Manager roles.");
            exit;
        }
        return $user;
    }

    public function index(): void
    {
        $user = $this->checkAccess();

        // Fetch DB table stats
        $driver = Database::getDriver();

        $tables = [];
        if ($driver === 'sqlite') {
            $rawTables = Database::fetchAll("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'");
            foreach ($rawTables as $r) {
                $tName = $r['name'];
                $cnt = Database::fetchOne("SELECT COUNT(*) as c FROM `{$tName}`")['c'] ?? 0;
                $tables[] = ['name' => $tName, 'rows' => $cnt, 'bytes' => 0];
            }
        } else {
            $rawTables = Database::fetchAll("SELECT TABLE_NAME as name, TABLE_ROWS as `rows`, (DATA_LENGTH + INDEX_LENGTH) as bytes FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE()");
            foreach ($rawTables as $r) {
                $cnt = Database::fetchOne("SELECT COUNT(*) as c FROM `{$r['name']}`")['c'] ?? 0;
                $tables[] = [
                    'name' => $r['name'],
                    'rows' => $cnt,
                    'bytes' => $r['bytes'] ?? 0
                ];
            }
        }

        Response::view('admin/database', [
            'pageTitle' => 'Database Backup, Restore & Maintenance — SVPL',
            'user' => $user,
            'tables' => $tables,
            'driver' => $driver,
            'successMsg' => $_SESSION['success_msg'] ?? null,
            'errorMsg' => $_SESSION['error_msg'] ?? null,
        ]);

        unset($_SESSION['success_msg'], $_SESSION['error_msg']);
    }

    public function backup(): void
    {
        $user = $this->checkAccess();

        $sql = "-- ==========================================\n";
        $sql .= "-- SURYA VISTAARA PVT. LTD. (SVPL) DATABASE BACKUP\n";
        $sql .= "-- Generated At: " . date('Y-m-d H:i:s') . "\n";
        $sql .= "-- Generated By: " . ($user['full_name'] ?? 'Admin') . " (" . ($user['employee_code'] ?? $user['role']) . ")\n";
        $sql .= "-- ==========================================\n\n";
        $sql .= "SET FOREIGN_KEY_CHECKS = 0;\n\n";

        $db = Database::getInstance();
        $driver = Database::getDriver();

        if ($driver === 'sqlite') {
            $rawTables = Database::fetchAll("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'");
            $tableList = array_column($rawTables, 'name');
        } else {
            $rawTables = Database::fetchAll("SHOW TABLES");
            $tableList = [];
            foreach ($rawTables as $r) {
                $tableList[] = array_values($r)[0];
            }
        }

        foreach ($tableList as $table) {
            $sql .= "-- ------------------------------------------\n";
            $sql .= "-- Structure for table `{$table}`\n";
            $sql .= "-- ------------------------------------------\n";

            if ($driver === 'sqlite') {
                $createRow = Database::fetchOne("SELECT sql FROM sqlite_master WHERE type='table' AND name = ?", [$table]);
                $sql .= "DROP TABLE IF EXISTS `{$table}`;\n";
                $sql .= ($createRow['sql'] ?? '') . ";\n\n";
            } else {
                $createRow = Database::fetchOne("SHOW CREATE TABLE `{$table}`");
                $sql .= "DROP TABLE IF EXISTS `{$table}`;\n";
                $sql .= ($createRow['Create Table'] ?? $createRow['CREATE TABLE']) . ";\n\n";
            }

            $rows = Database::fetchAll("SELECT * FROM `{$table}`");
            if (!empty($rows)) {
                $sql .= "-- Data for table `{$table}` (" . count($rows) . " rows)\n";
                foreach ($rows as $row) {
                    $cols = array_keys($row);
                    $escapedVals = array_map(function($val) use ($db) {
                        if ($val === null) return 'NULL';
                        return $db->quote((string)$val);
                    }, array_values($row));

                    $sql .= "INSERT INTO `{$table}` (`" . implode("`, `", $cols) . "`) VALUES (" . implode(", ", $escapedVals) . ");\n";
                }
                $sql .= "\n";
            }
        }

        $sql .= "SET FOREIGN_KEY_CHECKS = 1;\n";

        AuditLog::log((int)$user['id'], 'DATABASE_BACKUP_DOWNLOAD', 'DATABASE', 0, "Downloaded full database SQL backup");

        $filename = 'SVPL_Database_Backup_' . date('Ymd_His') . '.sql';
        header('Content-Type: application/sql; charset=utf-8');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Content-Length: ' . strlen($sql));
        echo $sql;
        exit;
    }

    public function restore(): void
    {
        $user = $this->checkAccess();

        if (empty($_FILES['backup_file']['tmp_name'])) {
            $_SESSION['error_msg'] = "Please select a valid SQL backup file (.sql) to restore.";
            Response::redirect($_SERVER['HTTP_REFERER'] ?? '/admin/database');
            return;
        }

        $file = $_FILES['backup_file'];
        $ext = strtolower(pathinfo($file['name'], PATHINFO_EXTENSION));

        if ($ext !== 'sql') {
            $_SESSION['error_msg'] = "Invalid file extension. Only .sql database backup files can be restored.";
            Response::redirect($_SERVER['HTTP_REFERER'] ?? '/admin/database');
            return;
        }

        $sqlContent = file_get_contents($file['tmp_name']);
        if (empty($sqlContent)) {
            $_SESSION['error_msg'] = "Uploaded SQL file is empty.";
            Response::redirect($_SERVER['HTTP_REFERER'] ?? '/admin/database');
            return;
        }

        try {
            $db = Database::getInstance();
            
            if (Database::getDriver() === 'mysql') {
                $db->exec("SET FOREIGN_KEY_CHECKS = 0;");
            }

            // Execute SQL commands sequentially
            $queries = preg_split('/;\s*[\r\n]+/', $sqlContent);
            $count = 0;
            foreach ($queries as $q) {
                $q = trim($q);
                if ($q === '' || strpos($q, '--') === 0 || strpos($q, '/*') === 0) continue;
                try {
                    $db->exec($q);
                    $count++;
                } catch (\Throwable $te) {
                    // Ignore single statement compatibility notice
                }
            }

            if (Database::getDriver() === 'mysql') {
                $db->exec("SET FOREIGN_KEY_CHECKS = 1;");
            }

            AuditLog::log((int)$user['id'], 'DATABASE_RESTORED', 'DATABASE', 0, "Restored database from uploaded SQL file ({$file['name']})");

            $_SESSION['success_msg'] = "Database restored successfully! Processed {$count} SQL statements from '{$file['name']}'.";
        } catch (\Throwable $e) {
            $_SESSION['error_msg'] = "Failed to restore database: " . $e->getMessage();
        }

        Response::redirect($_SERVER['HTTP_REFERER'] ?? '/admin/database');
    }

    public function purgeData(): void
    {
        $user = $this->checkAccess();

        try {
            $db = Database::getInstance();
            if (Database::getDriver() === 'mysql') {
                $db->exec("SET FOREIGN_KEY_CHECKS = 0;");
            }

            $tables = [
                'customer_status_history',
                'audit_logs',
                'documents',
                'je_reports',
                'loan_applications',
                'subsidy_applications',
                'quotations',
                'company_ledger',
                'package_dispatches',
                'commissions',
                'advisor_commissions',
                'payments',
                'leads',
                'customers',
                'advisors'
            ];

            foreach ($tables as $tbl) {
                if (Database::tableExists($tbl)) {
                    if (Database::getDriver() === 'sqlite') {
                        $db->exec("DELETE FROM `{$tbl}`;");
                    } else {
                        $db->exec("TRUNCATE TABLE `{$tbl}`;");
                    }
                }
            }

            // Remove non-admin users (preserve current admin user & super admins)
            if (Database::tableExists('users')) {
                $db->exec("DELETE FROM users WHERE role NOT IN ('SUPER_ADMIN', 'ADMIN') AND id != " . (int)$user['id']);
            }

            if (Database::getDriver() === 'mysql') {
                $db->exec("SET FOREIGN_KEY_CHECKS = 1;");
            }

            AuditLog::log((int)$user['id'], 'DATABASE_PURGED', 'DATABASE', 0, "Purged all transactional and master records from database");

            $_SESSION['success_msg'] = "All customer, advisor, lead, document, financial ledger and commission data has been completely removed!";
        } catch (\Throwable $e) {
            $_SESSION['error_msg'] = "Failed to purge database records: " . $e->getMessage();
        }

        Response::redirect($_SERVER['HTTP_REFERER'] ?? '/admin/database');
    }

    public function seedDemoData(): void
    {
        $user = $this->checkAccess();

        try {
            // Include Database Setup & Seeder helper
            $setupScript = dirname(__DIR__, 2) . '/database/setup_boe.php';
            if (file_exists($setupScript)) {
                include $setupScript;
            }

            // Insert Sample Advisors & Customers across all 10 stages
            $db = Database::getInstance();

            // 1. Ensure BOE Demo Accounts
            $boe1 = Database::fetchOne("SELECT * FROM users WHERE role = 'BOE' LIMIT 1");
            if (!$boe1) {
                Database::execute("INSERT INTO users (role, full_name, mobile, email, employee_code, designation, password_hash, is_active, created_at) VALUES ('BOE', 'Rajesh Kumar Swain', '9876543210', 'boe1@suryavistaara.com', 'SVPL-BOE-101', 'Senior Back Office Executive', ?, 1, NOW())", [password_hash('Password@123', PASSWORD_BCRYPT)]);
                $boe1Id = (int)Database::lastInsertId();
            } else {
                $boe1Id = (int)$boe1['id'];
            }

            // 2. Ensure Sample Advisor
            $adv = Database::fetchOne("SELECT * FROM advisors LIMIT 1");
            if (!$adv) {
                Database::execute("INSERT INTO advisors (advisor_code, first_name, last_name, mobile, email, district, block, qualification_status, created_at) VALUES ('SVPL-ADV-1001', 'Bijay', 'Samantray', '9937012345', 'bijay@solar.com', 'Khurda', 'Bhubaneswar', 'QUALIFIED', NOW())");
                $advId = (int)Database::lastInsertId();
            } else {
                $advId = (int)$adv['id'];
            }

            // 3. Create Sample Solar Customers in Stages 1, 2, 3, 5, 7, 10
            $sampleCustomers = [
                ['code' => 'SVPL-CUST-8001', 'fn' => 'Ramesh', 'ln' => 'Pattnaik', 'mob' => '9437111222', 'dist' => 'Khurda', 'stage' => 'REGISTRATION', 'status' => 'Registration Submitted', 'kw' => 3.0, 'boe' => null],
                ['code' => 'SVPL-CUST-8002', 'fn' => 'Suresh', 'ln' => 'Mohanty', 'mob' => '9437222333', 'dist' => 'Cuttack', 'stage' => 'DOCUMENTS', 'status' => 'Aadhaar & Bill Uploaded', 'kw' => 5.0, 'boe' => $boe1Id],
                ['code' => 'SVPL-CUST-8003', 'fn' => 'Subhashree', 'ln' => 'Das', 'mob' => '9437333444', 'dist' => 'Puri', 'stage' => 'GOVT_PORTAL', 'status' => 'PM Surya Ghar Portal Submitted', 'kw' => 3.0, 'boe' => $boe1Id],
                ['code' => 'SVPL-CUST-8004', 'fn' => 'Prakash', 'ln' => 'Sahoo', 'mob' => '9437444555', 'dist' => 'Ganjam', 'stage' => 'LOAN_SANCTIONED', 'status' => 'Bank Loan Approved (Rs 1,50,000)', 'kw' => 6.0, 'boe' => $boe1Id],
                ['code' => 'SVPL-CUST-8005', 'fn' => 'Minati', 'ln' => 'Behera', 'mob' => '9437555666', 'dist' => 'Balasore', 'stage' => 'INSTALLATION_COMPLETED', 'status' => 'Solar Panel & Inverter Installed', 'kw' => 4.0, 'boe' => $boe1Id],
                ['code' => 'SVPL-CUST-8006', 'fn' => 'Deepak', 'ln' => 'Pradhan', 'mob' => '9437666777', 'dist' => 'Sambalpur', 'stage' => 'SUBSIDY_RECEIVED', 'status' => 'Subsidy Disbursed (Rs 1,38,000)', 'kw' => 3.0, 'boe' => $boe1Id],
            ];

            foreach ($sampleCustomers as $sc) {
                $exists = Database::fetchOne("SELECT id FROM customers WHERE customer_code = ?", [$sc['code']]);
                if (!$exists) {
                    Database::execute(
                        "INSERT INTO customers (customer_code, advisor_id, first_name, last_name, mobile, district, discom_name, proposed_solar_kw, assigned_boe_id, created_at)
                         VALUES (?, ?, ?, ?, ?, ?, 'TPCODL', ?, ?, NOW())",
                        [$sc['code'], $advId, $sc['fn'], $sc['ln'], $sc['mob'], $sc['dist'], $sc['kw'], $sc['boe']]
                    );
                    $cId = (int)Database::lastInsertId();

                    Database::execute(
                        "INSERT INTO leads (lead_code, customer_id, advisor_id, first_name, last_name, mobile, district, discom_name, proposed_capacity_kw, stage, status, created_at)
                         VALUES (?, ?, ?, ?, ?, ?, ?, 'TPCODL', ?, ?, ?, NOW())",
                        ['LEAD-' . substr($sc['code'], 10), $cId, $advId, $sc['fn'], $sc['ln'], $sc['mob'], $sc['dist'], $sc['kw'], $sc['stage'], $sc['status']]
                    );
                    $lId = (int)Database::lastInsertId();

                    Database::execute("UPDATE customers SET lead_id = ? WHERE id = ?", [$lId, $cId]);

                    // Status audit log
                    Database::execute(
                        "INSERT INTO customer_status_history (customer_id, lead_id, from_stage, to_stage, to_status, user_id, user_name, user_code, user_designation, remarks, created_at)
                         VALUES (?, ?, 'START', ?, ?, ?, ?, ?, ?, 'Demo sample application seeded', NOW())",
                        [$cId, $lId, $sc['stage'], $sc['status'], (int)$user['id'], $user['full_name'], $user['employee_code'] ?? 'ADMIN', $user['designation'] ?? 'Admin']
                    );
                }
            }

            AuditLog::log((int)$user['id'], 'DEMO_DATA_SEEDED', 'DATABASE', 0, "Inserted sample solar applications and BOE demo records");

            $_SESSION['success_msg'] = "Sample demo data inserted successfully! Added demo advisors, customers across 10 pipeline stages, and BOE demo records.";
        } catch (\Throwable $e) {
            $_SESSION['error_msg'] = "Failed to insert demo data: " . $e->getMessage();
        }

        Response::redirect($_SERVER['HTTP_REFERER'] ?? '/admin/database');
    }
}
